//
//  MovieModels.swift
//  TheCleanMovie
//
//  Created by Giuliano Accorsi on 04/03/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

struct MoviesEntity: Codable {
    
    let page: Int
    let totalMovies: Int
    let totalPages: Int
    let movieList: [MovieEntity]

    enum CodingKeys: String, CodingKey {
        case page
        case totalMovies = "total_results"
        case totalPages = "total_pages"
        case movieList = "results"
    }
}

